### ISSUE TITLE
Page scrolls while going to next step

### ISSUE THREAD

**Issue by dani0332** [mstratman/jQuery-Smart-Wizard#119]
I am using **SmartWizard v4.3.1** and when I click next or previous button the page scrolls up to the extent where the **`step`** element is at the top of the page. Below is a screenshot what I am getting,

**I want the page to stay where it is,** I know the scrolling is happening due to anchor having an `id=""` attribute. But I've tried everything but couldn't make it stop.
![capture](https://user-images.githubusercontent.com/25737126/39327123-849581b2-49b0-11e8-8d09-c1408d06b614.JPG)

**Comment by dale-french** [comment]
How did you fix this? Having the same issue.

**Comment by dani0332** [comment]
I don't exactly remember. But I think I didn't put `tab-pane` inside `tab-content` , which was causing the issue. You can also  `e.preventDefault()` of jQuery
