### ISSUE TITLE
setting custom height on step box

### ISSUE THREAD

**Issue by 0101adm** [mstratman/jQuery-Smart-Wizard#47]
its defaulted to 300px.

how can i set the height to something else?

tried the css file but nothing yet.

**Comment by miyan27** [comment]
you can add onShowStep on your option parameters, and link it to the function that included the css function for example :
$('#wizard').smartWizard({
            transitionEffect: 'slideleft',
            keyNavigation: false,
            labelNext: 'next',
            labelPrevious: 'back',
            labelFinish: 'send',
            onLeaveStep: function 1,
            onShowStep: function 2,
            onFinish: function 3
        });

function 2(){
$("#wizard").smartWizard("fixHeight"); //if you want to delete the defaulted height or~
$('write your id name in here').css({
                    'height': '15px'});  //if you want to add some css
}
