### ISSUE TITLE
Request more details on cycleSteps option in jquery-Smart Wizard

### ISSUE THREAD

**Issue by YochanaSH** [mstratman/jQuery-Smart-Wizard#83]
Hi There,

Can anyone provide an example / or a scenario where cycleSteps can be used ? I would like t better understand this option

Many Thanks !

**Comment by mstratman** [comment]
I think perhaps in a scenario such as adding multiple collections of records. The confirmation button on the last step might be something like "Save and add another" which takes you back to the beginning
