### ISSUE TITLE
go to next or prev step on click inside content 

### ISSUE THREAD

**Issue by spostad7** [mstratman/jQuery-Smart-Wizard#85]
hi, tanx for your smart wizard :+1: 
I have a problem that I didn't find any function for it. I have specific element (eg: links, buttons,...) inside content (I mean div.content). I want when user click on them, he could go to next or prev step. how can I solve it?!
tanx

**Comment by mstratman** [comment]
You can manually call methods as described in the "Public methods:" section of the readme here: https://github.com/mstratman/jQuery-Smart-Wizard

e.g. `$('#wizard').smartWizard('goForward');` or goBackward, or goToStep

**Comment by spostad7** [comment]
ok, but how can I set it to click function!? for example when the '.btn' clicked, it go forward...
how can I do that?

**Comment by spostad7** [comment]
I got it ;)
tanq
