### ISSUE TITLE
Show finish button only on last step

### ISSUE THREAD

**Issue by sharathdaniel** [mstratman/jQuery-Smart-Wizard#87]
I tried different methods and looked on the documentation, i cannot figure out to do this.

**Comment by mstratman** [comment]
You can either manually hide it via CSS, or add a new method to create it and wire up its events.

**Comment by onesinus** [comment]
Hei,

I just found this solutions,
just add this simple code in every step in wizard

```
if($('button.sw-btn-next').hasClass('disabled')){
				$('.sw-btn-group-extra').show(); // show the button extra only in the last page
			}else{
				$('.sw-btn-group-extra').hide();				
			}
```

Here Is The Full Code :

```
$("#smartwizard").on("showStep", function(e, anchorObject, stepNumber, stepDirection) {
			if($('button.sw-btn-next').hasClass('disabled')){
				$('.sw-btn-group-extra').show(); // show the button extra only in the last page
			}else{
				$('.sw-btn-group-extra').hide();				
			}

	      });
```

The Explanation is so simple,showStep function handle every step in wizard ( from step 1 to 2, etc )
Then we just need to check is button with class btn-next(class next button) has disabled class, as we know the next button disabled when the page is last.

Hope this help.

**Comment by mazharkhan3** [comment]
@onesinus Thanks for the snippet.

**Comment by 1999fronda** [comment]
thanks for the snippet
