### ISSUE TITLE
Cannot set property 'contentWidth' of undefined

### ISSUE THREAD

**Issue by SBrownAU** [mstratman/jQuery-Smart-Wizard#94]
When initializing:

```
Uncaught TypeError: Cannot set property 'contentWidth' of undefined

...

// 'this' is undefined
this.contentWidth = $this.elmStepContainer.width();
```

**Comment by mstratman** [comment]
Do you have a full example that reproduces this problem?

**Comment by SBrownAU** [comment]
Closing the issue. Was trying to load smart wizard within a Vue component. Couldn't find a way to do it, so now loading outside the component.
