### ISSUE TITLE
More examples does not work out of the box

### ISSUE THREAD

**Issue by juniorojha** [mstratman/jQuery-Smart-Wizard#98]
Please make following changes for more examples to work out of the box - 

<pre>< script type="text/javascript" src="js/jquery-1.4.2.min.js" >< / script >
< script type="text/javascript" src="js/jquery.smartWizard-2.0.min.js" >< / script ></pre>

These links are outdated. Jquery included is now v2.0.0 and is included in ../js/ folder which is outside of the more_examples folder.

**Comment by mstratman** [comment]
This isn't being actively developed. Submit a pull request and I'll merge, thanks.
