### ISSUE TITLE
Proper method to hide wizard until page loaded

### ISSUE THREAD

**Issue by StateBarofArizona** [mstratman/jQuery-Smart-Wizard#99]
By default, my plain vanilla ugly HTML is displayed on the screen, then after the page loads, the wizard script cleans things up and correctly formats everything.  What is the proper way to hide the wizard contents until the page is loaded and the HTML formatted properly?  I tried hiding the wizard div by default and display after page load.  This works as long as you are not using fixHeight.  Otherwise, fixHeight fails and you end up with a wizard that is visible but too short.

**Comment by FuzzyCoder** [comment]
Hello-
Were you able to find a solution to this issue?

**Comment by StateBarofArizona** [comment]
I did.  I noticed there is code in the wizard for loading but I have not found any documentation.  Instead I added a loading.gif into a div, hide the wizard by default and then upon page load, hide the loading div and display the wizard.

Connie DeCinko, Programmer Analyst
T: 602.340.7290  F: 602.416.7490

**Comment by FuzzyCoder** [comment]
Thank you.  That helps.

**Comment by mstratman** [comment]
Closing but feel free to reopen if needed
